import { Backgrounds } from '../../types/backgrounds'

export const defaultBackgrounds: Backgrounds[] = [
  {
    id: 'city_fire',
    prompt: 'gen_background_replace:prompt_city%20on%20fire',
    plain_prompt: 'city%20on%20fire',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/city_fire.png',
    description: 'City on fire',
  },
  {
    id: 'halloween',
    prompt: 'gen_background_replace:prompt_halloween%20decoration',
    plain_prompt: 'halloween decoration',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/halloween.png',
    description: 'Halloween',
  },
  {
    id: 'hell',
    prompt: 'gen_background_replace:prompt_hell',
    plain_prompt: 'hell',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/hell.png',
    description: 'Hell',
  },
  {
    id: 'steampunk',
    prompt: 'gen_background_replace:prompt_steampunk%20overhaul',
    plain_prompt: 'steampunk overhaul',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/steampunk.png',
    description: 'Steampunk',
  },
  {
    id: 'fantasy',
    prompt: 'gen_background_replace:prompt_fantasy%20landscape',
    plain_prompt: 'fantasy landscape',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/fantasy.png',
    description: 'Fantasy',
  },
  {
    id: 'colorful_shapes',
    prompt: 'gen_background_replace:prompt_colorful%20shapes',
    plain_prompt: 'colorful shapes',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/colorful_shapes.png',
    description: 'Colorful shapes',
  },
  {
    id: 'mountains',
    prompt: 'gen_background_replace:prompt_mountains',
    plain_prompt: 'mountains',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/mountains.png',
    description: 'Mountains',
  },
  {
    id: 'beach',
    prompt: 'gen_background_replace:prompt_beach',
    plain_prompt: 'beach',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/beach.png',
    description: 'Beach',
  },
  {
    id: 'vintage_paper_effect',
    prompt: 'gen_background_replace:prompt_vintage%20paper%20effect',
    plain_prompt: 'vintage paper effect',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/vintage_paper_effect.png',
    description: 'Vintage paper effect',
  },
  {
    id: 'monocromatic_with_accent_color',
    prompt:
      'gen_background_replace:prompt_monocromatic%20city%20with%20accent%20color',
    plain_prompt: 'monocromatic city with accent color',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/monocromatic_with_accent_color.png',
    description: 'Monocromatic with accent color',
  },
  {
    id: 'galaxy',
    prompt: 'gen_background_replace:prompt_galaxy',
    plain_prompt: 'galaxy',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/galaxy.png',
    description: 'Galaxy',
  },
  {
    id: 'cyberpunk',
    prompt: 'gen_background_replace:prompt_cyberpunk',
    plain_prompt: "cyberpunk city",
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/cyberpunk.png',
    description: 'Cyberpunk',
  },
  {
    id: 'forest',
    prompt: 'gen_background_replace:prompt_forest',
    plain_prompt: 'forest',
    url: 'https://res.cloudinary.com/dr0ujyp54/image/upload/v1729186981/backgrounds/forest.png',
    description: 'Forest',
  },
]
